---
# tasks file for molecule-validate-neutron-deploy
- name: Clone openstack-ansible-ops repo
  git:
    repo=https://github.com/openstack/openstack-ansible-ops.git
    dest=/opt/openstack-ansible-ops
- name: Create networks
  shell: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i /opt/openstack-ansible/playbooks/inventory/dynamic_inventory.py --tags create_networks openstack-service-setup.yml
  args:
    executable: /bin/bash
    chdir: /opt/openstack-ansible-ops/multi-node-aio-xenial-ansible/playbooks/
